# Generated by Django 3.2.4 on 2021-06-16 20:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre Artista')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Descripcion')),
                ('img_artista', models.ImageField(upload_to='images/artista', verbose_name='Imagen Artista')),
            ],
        ),
        migrations.CreateModel(
            name='Pintura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre Pintura')),
                ('historia', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Historia')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Descripcion')),
                ('img_pintura', models.ImageField(upload_to='images/pintura', verbose_name='Imagen Pintura')),
                ('precio', models.FloatField(default=0.0, verbose_name='Precio')),
                ('tecnica', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Tecnica')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artista')),
            ],
        ),
    ]
