# Generated by Django 3.2.4 on 2021-06-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210616_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='img_artista',
            field=models.ImageField(upload_to='core/img', verbose_name='Imagen Artista'),
        ),
        migrations.AlterField(
            model_name='pintura',
            name='img_pintura',
            field=models.ImageField(upload_to='core/img', verbose_name='Imagen Pintura'),
        ),
    ]
