# Generated by Django 3.2.4 on 2021-07-07 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210616_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre Usuario')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
            ],
        ),
    ]
